name: "Flashforge Adventurer 5M Control Panel"
version: "1.2.1"
slug: "flashforge_5m_panel"
description: "Интеграция и UI-панель для управления 3D-принтером Flashforge Adventurer 5M на базе Klipper/Moonraker"
url: "https://github.com/setapka/ha-flashforge-addon"
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.14
  amd64: ghcr.io/home-assistant/amd64-base:3.14
  armv7: ghcr.io/home-assistant/armv7-base:3.14
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:printer-3d"
panel_title: "Adventurer 5M"
network:
  8099/tcp: 8099
host_network: true
hassio_api: true
hassio_role: default
options:
  printer_ip: ""
  printer_port: 8899
  scan_ports: "8899"
  log_level: "error"
schema:
  printer_ip: "str?"
  printer_port: "int"
  scan_ports: "str?"
  log_level: "list(error|warning|info|debug)"
map:
  - ssl:ro
startup: application
boot: auto
watchdog: http://[HOST]:[PORT:8099]/health
